[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
hackatom_webdex = "366X1g31WNniz8dPY51DXxg9dR4gcKeoBjyHvcbdyxr7"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "http://127.0.0.1:8899"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run mocha -t 1000000 tests/"

[test]
startup_wait = 120